const dummyData = [
    {
        'id': '0',
        'title': 'Apex Legends',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/capsule_616x353.jpg?t=1660674992',
        'description': 'Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.',
        'tags': 'Battle Royale, FPS, Multiplayer',
        'cost': 'Free to Play',
    },
    {
        'id': '1',
        'title': 'Elden Ring',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg?t=1654259241',
        'description': 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
        'tags': 'RPG, Difficult, Action',
        'cost': '$59.99',
    },
    {
        'id': '2',
        'title': 'Final Fantasy XIV Online',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/39210/capsule_616x353.jpg?t=1646695302',
        'description': 'Take part in an epic and ever-changing FINAL FANTASY as you adventure and explore with friends from around the world.',
        'tags': 'MMORPG, Action, Social',
        'cost': '$19.99',
    },
    {
        'id': '3',
        'title': 'Hades',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/capsule_616x353.jpg?t=1661549369',
        'description': 'Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre.',
        'tags': 'RogueLike, Difficult, Action',
        'cost': '$24.99',
    },
    {
        'id': '4',
        'title': 'The Elder Scrolls V: Skyrim',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/489830/capsule_616x353.jpg?t=1650909796',
        'description': 'The next chapter in the highly anticipated Elder Scrolls saga arrives from the makers of the 2006 and 2008 Games of the Year, Bethesda Game Studios. Skyrim reimagines and revolutionizes the open-world fantasy epic, bringing to life a complete virtual world open for you to explore any way you choose.',
        'tags': 'RPG, Open World, Adventure',
        'cost': '$19.99',
    },
    {
        'id': '5',
        'title': 'Red Dead Redemption 2',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg?t=1656615305',
        'description': 'Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age.',
        'tags': 'Open World, Story Rich, Western',
        'cost': '$59.99',
    },
    {
        'id': '6',
        'title': 'Stardew Valley',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/440820/capsule_616x353.jpg?t=1581550226',
        'description': 'You have inherited your grandfathers old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?',
        'tags': 'RPG, Farming, 2D',
        'cost': '$14.99',
    },
    {
        'id': '7',
        'title': 'Terraria',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/105600/capsule_616x353.jpg?t=1590092560',
        'description': 'Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!',
        'tags': 'Sandbox, 2D, Open World',
        'cost': '$9.99',
    },
    {
        'id': '8',
        'title': 'SMITE',
        'image': 'https://cdn.akamai.steamstatic.com/steam/apps/387440/capsule_616x353.jpg?t=1585774693',
        'description': 'Join 35+ million players in SMITE, the Battleground of the Gods! Wield Thor’s hammer, turn your foes to stone as Medusa, or flex your divine power as one of 100+ other mythological icons. Become a God and play FREE today!',
        'tags': 'MOBA, Multiplayer, Action',
        'cost': 'Free to Play',
    },
    {
        'id': '9',
        'title': 'Fallout 4',
        'image': 'https://s3.gaming-cdn.com/images/products/755/orig/fallout-4-pc-game-steam-cover.jpg?v=1647341100',
        'description': 'Bethesda Game Studios, the award-winning creators of Fallout 3 and The Elder Scrolls V: Skyrim, welcome you to the world of Fallout 4 – their most ambitious game ever, and the next generation of open-world gaming.',
        'tags': 'Story Rich, Open World, RPG',
        'cost': '$19.99',
    },
    {
        'id': '10',
        'title': 'The Witcher 3: Wild Hunt',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1229320/capsule_616x353.jpg?t=1659615500',
        'description': 'As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world.',
        'tags': 'Open World, RPG, Story Rich',
        'cost': '$39.99',
    },
    {
        'id': '11',
        'title': 'Raft',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/648800/capsule_616x353.jpg?t=1642416570',
        'description': 'Raft throws you and your friends into an epic oceanic adventure! Alone or together, players battle to survive a perilous voyage across a vast sea! Gather debris, scavenge reefs and build your own floating home, but be wary of the man-eating sharks!',
        'tags': 'Survival, Open World, Multiplayer',
        'cost': '$19.99',
    },

]

export default dummyData;