export const dummyData = [
    {
        'id': '0',
        'title': 'Apex Legends',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/capsule_616x353.jpg?t=1660674992',
        'description': 'Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.',
        'tags': 'Battle Royale',
        'cost': 'Free to Play',
    },
    {
        'id': '1',
        'title': 'Elden Ring',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/capsule_616x353.jpg?t=1654259241',
        'description': 'THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
        'tags': 'RPG',
        'cost': '$59.99',
    },
    {
        'id': '2',
        'title': 'Final Fantasy XIV Online',
        'image': 'https://cdn.cloudflare.steamstatic.com/steam/apps/39210/capsule_616x353.jpg?t=1646695302',
        'description': 'Take part in an epic and ever-changing FINAL FANTASY as you adventure and explore with friends from around the world.',
        'tags': 'MMORPG',
        'cost': '$19.99',
    },
    {
        'id': '3',
        'title': '',
        'image': '',
        'description': '',
        'tags': '',
        'cost': '',
    },
    {
        'id': '4',
        'title': '',
        'image': '',
        'description': '',
        'tags': '',
        'cost': '',
    },
    {
        'id': '5',
        'title': '',
        'image': '',
        'description': '',
        'tags': '',
        'cost': '',
    },
    {
        'id': '6',
        'title': '',
        'image': '',
        'description': '',
        'tags': '',
        'cost': '',
    },
    {
        'id': '7',
        'title': '',
        'image': '',
        'description': '',
        'tags': '',
        'cost': '',
    },
    {
        'id': '8',
        'title': '',
        'image': '',
        'description': '',
        'tags': '',
        'cost': '',
    },
    {
        'id': '9',
        'title': '',
        'image': '',
        'description': '',
        'tags': '',
        'cost': '',
    },

]